fix: cleanup commented out shit
Signed-off-by: Nicholas Sielicki <nix@opensource.nslick.com>

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -8,7 +8,7 @@ on:
     branches: [main]
 
 concurrency:
-  group: ${{ github.workflow }}-${{ github.ref }}
+  group: ${{ github.workflow }}
   cancel-in-progress: true
 
 jobs:
@@ -25,15 +25,15 @@ jobs:
         with:
           determinate: true
       - name: build prerelease detsys nix
-        run: nix build github:DeterminateSystems/nix-src/flake-schemas
+        run: nix build .#nix
       - name: flake-schemas show
-        run: nix run github:DeterminateSystems/nix-src/flake-schemas --   flake show . --all-systems
+        run: nix run .#nix --   flake show . --all-systems
       - name: flake-schemas check
-        run: nix run github:DeterminateSystems/nix-src/flake-schemas --   flake check . --all-systems
+        run: nix run .#nix --   flake check . --all-systems
       - name: tests
         run: |
-          (nix run github:DeterminateSystems/nix-src/flake-schemas -- flake check --impure --override-input dogrules "git+file://$(pwd)" ./test/fail && echo "BAD: fail passed" && exit 1) || (echo "GOOD: fail failed as desired")
-          (nix run github:DeterminateSystems/nix-src/flake-schemas -- flake check --impure --override-input dogrules "git+file://$(pwd)" ./test/good && echo "GOOD: good passed") || (echo "BAD: good failed" && exit 1)
+          (nix run .#nix -- flake check --impure --override-input dogrules "git+file://$(pwd)" ./test/fail && echo "BAD: fail passed" && exit 1) || (echo "GOOD: fail failed as desired")
+          (nix run .#nix -- flake check --impure --override-input dogrules "git+file://$(pwd)" ./test/good && echo "GOOD: good passed") || (echo "BAD: good failed" && exit 1)
       - name: Push to FlakeHub
         uses: DeterminateSystems/flakehub-push@main
         with:
